language: groovy

install:
  - ./gradlew -q assemble --stacktrace --no-daemon

script:
  - ./gradlew pTML test integrationTest --stacktrace --no-daemon

jdk:
  - oraclejdk8
# weird probs with openjdk
#  - openjdk7
#  - oraclejdk7
